# Generated by Django 4.0.6 on 2026-09-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduationDate', models.DateField(verbose_name='Graduation Date')),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=3, max_digits=4)),
                ('additionalInfo', models.TextField(verbose_name='Additional Info')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200)),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('briefDescription', models.CharField(max_length=500, verbose_name='Brief Description')),
                ('content', models.TextField()),
                ('githubLink', models.URLField(blank=True, null=True, verbose_name='Github Link')),
                ('html_project', models.BooleanField(default=False, verbose_name='HTML Project')),
                ('demoVideo', models.FileField(blank=True, null=True, upload_to='demoVideo', verbose_name='Demo Video')),
                ('language', models.CharField(default='Unspecified', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(height_field='height', upload_to='ProjectImage', width_field='width')),
                ('mainImage', models.BooleanField(default=False, verbose_name='Main Image')),
                ('linkedProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('relatedJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectimage',
            constraint=models.UniqueConstraint(condition=models.Q(('mainImage', True)), fields=('linkedProject',), name='unique_main_image'),
        ),
    ]
