# Generated by Django 5.2.17 on 2026-09-18 18:38

from django.db import migrations, models
from django.utils.text import slugify


# slugify() strips symbols outright, so "C#" becomes "c" and "C++" becomes "c".
# Spelling them first keeps the filter values readable and distinct.
SLUG_SUBSTITUTIONS = (("++", " plus plus"), ("#", " sharp"), ("&", " and "))


def _slug_source(text):
    for symbol, words in SLUG_SUBSTITUTIONS:
        text = text.replace(symbol, words)

    return text


def backfill_skill_slugs(apps, schema_editor):
    """Slugs for skills that predate the field.

    Deliberately does not import Skill.save: historical migrations must not
    depend on current model code.
    """
    Skill = apps.get_model("main", "Skill")

    taken = set()
    for skill in Skill.objects.order_by("pk"):
        base = slugify(_slug_source(skill.skill)) or "skill"
        slug = base
        suffix = 2
        while slug in taken:
            slug = f"{base}-{suffix}"
            suffix += 1

        taken.add(slug)
        skill.slug = slug
        skill.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_is_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('category', 'sort_order', 'skill')},
        ),
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(blank=True, help_text='Leave blank for ongoing work.', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text="Featured projects lead the portfolio page under 'Selected work'."),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Capabilities drive the portfolio filter. Platforms and tooling show as tags.', related_name='projects', to='main.skill', verbose_name='Capabilities and tools'),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(blank=True, help_text='Optional. Used to order projects and to show when the work happened.', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('capability', 'Capability'), ('language', 'Language'), ('platform', 'Framework or platform'), ('tooling', 'Tooling'), ('practice', 'Ways of working')], default='language', help_text='Only capabilities drive the portfolio filter.', max_length=20),
        ),
        # Three steps, not one: adding a unique column to existing rows gives
        # every one of them the same empty default and the constraint fails.
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Used as the filter value and in portfolio URLs. Generated from the name.', max_length=220),
        ),
        migrations.RunPython(backfill_skill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, help_text='Used as the filter value and in portfolio URLs. Generated from the name.', max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower sorts first within a category. Ties fall back to the name.'),
        ),
    ]
