# Generated by Django 5.2.17 on 2026-09-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seed_capabilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-graduationDate',)},
        ),
        migrations.AddField(
            model_name='education',
            name='credential_type',
            field=models.CharField(choices=[('degree', 'Degree'), ('certificate', 'Certificate')], default='degree', max_length=20, verbose_name='Credential type'),
        ),
        migrations.AlterField(
            model_name='education',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to omit it from the page.', max_digits=4, null=True, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='education',
            name='additionalInfo',
            field=models.TextField(blank=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200, verbose_name='Credential'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduationDate',
            field=models.DateField(verbose_name='Completion Date'),
        ),
    ]
