# Generated by Django 5.2.17 on 2026-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_leadership_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Personal projects are shown in the accent colour; professional ones in purple.', verbose_name='Personal project'),
        ),
    ]
