# Generated by Django 5.2.17 on 2026-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rest_api_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_ongoing_program',
            field=models.BooleanField(default=False, help_text="For work that runs continuously rather than finishing. Reads as 'Ongoing since ...' instead of '... – Present'.", verbose_name='Ongoing programme of work'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.CharField(blank=True, help_text='One line on what the work was worth — time saved, volume handled, what it replaced. Renders above the description, and is skipped entirely while blank.', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, help_text='Unpublished projects stay in the admin and never reach the site.'),
        ),
    ]
